plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.3'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
	id "org.sonarqube" version "6.0.1.5171"
}

group = 'co.edu.uniajc'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation("org.flywaydb:flyway-database-postgresql")
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'
	runtimeOnly 'org.postgresql:postgresql'

	// Junit
	testImplementation 'org.junit.jupiter:junit-jupiter-api'
	testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'

	// Mockito
	testImplementation 'org.mockito:mockito-core'
	testImplementation 'org.mockito:mockito-junit-jupiter'
}

jacocoTestReport {
	reports {
		xml.required = true
		html.required = true
	}

	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: [
					'co/edu/uniajc/model/**', // Exclude model classes
					'co/edu/uniajc/config/**', // Exclude config classes
					'co/edu/uniajc/Application.java', // Exclude main application class
					'co/edu/uniajc/controller/**' // Exclude controllers class.
			])
		}))
	}

	finalizedBy jacocoTestCoverageVerification
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			enabled = true
			limit {
				minimum = 0.80 // 80% coverage
			}
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

sonarqube {
	properties {
		property "sonar.projectKey", "davidalzate88:seminario1041B your_organization_key:your_project_key" // Replace with your actual keys
		property "sonar.organization", "davidalzate88" // Replace with your organization key
		property "sonar.host.url", "https://sonarcloud.io"
		property "sonar.login", "6cb74db5bc1ca19d3bc027f8be50caa210373791" // Replace with your SonarCloud token
		property "sonar.java.coveragePlugin", "jacoco"
		property "sonar.coverage.jacoco.xmlReportPaths", "${project.projectDir}/reports/jacoco/test/jacocoTestReport.xml"
		property "sonar.sources", "src/main/java"
		property "sonar.tests", "src/test/java"
		property "sonar.exclusions", "**/model/**, **/config/**, **/Application.java" // Add any exclusions you need
	}
}
