CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE "order"
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    total            DECIMAL,
    shipment_address VARCHAR(255),
    user_id          BIGINT,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE order_products
(
    order_id    BIGINT NOT NULL,
    products_id BIGINT NOT NULL
);

CREATE TABLE payment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_code VARCHAR(255),
    amount       DECIMAL,
    order_id     BIGINT,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE product
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    price         INTEGER,
    stock         VARCHAR(255),
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE product_category
(
    category_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL
);

CREATE TABLE role
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255),
    status BOOLEAN,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE user_rol
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    id_card_number VARCHAR(255),
    email          VARCHAR(255),
    cellphone      VARCHAR(255),
    address        VARCHAR(255),
    city           VARCHAR(255),
    postal_code    VARCHAR(255),
    creation_date  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE order_products
    ADD CONSTRAINT fk_ordpro_on_order FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE order_products
    ADD CONSTRAINT fk_ordpro_on_product FOREIGN KEY (products_id) REFERENCES product (id);

ALTER TABLE product_category
    ADD CONSTRAINT fk_procat_on_category FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE product_category
    ADD CONSTRAINT fk_procat_on_product FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE user_rol
    ADD CONSTRAINT fk_user_rol_on_role FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_rol
    ADD CONSTRAINT fk_user_rol_on_user FOREIGN KEY (user_id) REFERENCES users (id);

-- populate tables with Dummy data
INSERT INTO category (name) VALUES ('Electrica');

INSERT INTO role (name, status) VALUES ('Administrador', true);
INSERT INTO role (name, status) VALUES ('Cliente', true);